import {
  IsString,
  Matches,
  IsNotEmpty,
  IsOptional,
  ValidateNested,
  IsEnum,
  IsIn,
  MaxLength,
  MinLength,
} from 'class-validator';
import { Transform, Type } from 'class-transformer';
import { UserDevicePlatform } from '../../../database/entities/user-device.entity';

export class VerifyOtpDeviceDto {
  /** Raw device identifier (IMEI, Android ID, IDFV, etc.) — never stored. */
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  /**
   * Per-install random salt generated by the mobile app on first launch and
   * stored in secure storage.  Issued by DeviceFingerprintService.issueInstallSalt().
   */
  @IsString()
  @IsNotEmpty()
  installSalt: string;

  @IsEnum(UserDevicePlatform)
  platform: UserDevicePlatform;

  /** Firebase Cloud Messaging token for push delivery. */
  @IsOptional()
  @IsString()
  fcmToken?: string;

  /** ISO-639-1 locale of the device (e.g. "ar", "en"). */
  @IsOptional()
  @IsString()
  locale?: string;

  /** Human-readable device name set by the user (e.g. "My iPhone 14"). */
  @IsOptional()
  @IsString()
  label?: string;

  /**
   * Whether the device's location APIs are currently mocked (e.g. developer
   * options or a spoofing app).  Sent with the OTP payload so the backend can
   * immediately record the state and flag repeated offenders.
   */
  @IsOptional()
  isMockLocation?: boolean;
}

export class VerifyOtpDto {
  @IsString()
  @IsNotEmpty({ message: 'Phone number is required' })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @Matches(/^\+[1-9]\d{1,14}$/, {
    message: 'Phone number must be in E.164 format (e.g., +201234567890)',
  })
  phoneNumber: string;

  @IsString()
  @IsNotEmpty({ message: 'OTP code is required' })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @Matches(/^\d{6}$/, { message: 'OTP code must be exactly 6 digits' })
  code: string;

  /** Optional device binding payload.  When omitted no device row is created. */
  @IsOptional()
  @ValidateNested()
  @Type(() => VerifyOtpDeviceDto)
  device?: VerifyOtpDeviceDto;

  // ── Auto-registration fields (used only on first sign-up) ───────────────
  // Sent by the mobile sign-up screens so the backend can create a fresh user
  // record on the spot when no pending registration / existing user exists.
  // Ignored when an account is already provisioned.

  @IsOptional()
  @IsString()
  @MinLength(1)
  @MaxLength(120)
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  name?: string;

  @IsOptional()
  @IsString()
  @IsIn(['male', 'female'])
  gender?: string;

  @IsOptional()
  @IsString()
  @IsIn(['passenger', 'driver'])
  role?: string;

  @IsOptional()
  @IsString()
  @MinLength(8)
  @MaxLength(100)
  @Matches(/^(?=.*[A-Za-z])(?=.*\d).{8,}$/, {
    message:
      'Password must be at least 8 characters with at least one letter and one number',
  })
  password?: string;
}
