import 'reflect-metadata';
import { DataSource } from 'typeorm';
import {
  BookingEntity,
  CommunicationFeeEntity,
  DeviceTokenEntity,
  DriverLocationEntity,
  NotificationEntity,
  OtpCodeEntity,
  PasswordResetSessionEntity,
  PaymentEntity,
  PayoutRequestEntity,
  PendingRegistrationEntity,
  TripEntity,
  UserEntity,
  VehicleEntity,
  WalletAccountEntity,
  WalletHoldEntity,
  WalletTransactionEntity,
} from './entities';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.POSTGRES_HOST || 'localhost',
  port: Number(process.env.POSTGRES_PORT || 5432),
  username: process.env.POSTGRES_USER || 'postgres',
  password: process.env.POSTGRES_PASSWORD || 'postgres',
  database: process.env.POSTGRES_DB || 'rideshare',
  ssl:
    process.env.POSTGRES_SSL === 'true' ? { rejectUnauthorized: false } : false,
  entities: [
    UserEntity,
    TripEntity,
    BookingEntity,
    DriverLocationEntity,
    WalletAccountEntity,
    WalletTransactionEntity,
    WalletHoldEntity,
    PayoutRequestEntity,
    NotificationEntity,
    DeviceTokenEntity,
    PendingRegistrationEntity,
    OtpCodeEntity,
    VehicleEntity,
    PaymentEntity,
    CommunicationFeeEntity,
    PasswordResetSessionEntity,
  ],
  migrations: ['src/database/migrations/*.ts'],
});
