import 'reflect-metadata';
import { DataSource } from 'typeorm';
import {
  AccountFlagEntity,
  BookingEntity,
  BookingSeatEntity,
  CallSessionEntity,
  ChatRoomEntity,
  CommunicationFeeEntity,
  ComplaintEntity,
  DeviceTokenEntity,
  DriverLocationEntity,
  MessageEntity,
  NotificationEntity,
  OtpCodeEntity,
  PasswordResetSessionEntity,
  PaymentEntity,
  PayoutRequestEntity,
  PendingChargeEntity,
  PendingRegistrationEntity,
  RatingEntity,
  RefundRequestEntity,
  SecurityEventEntity,
  SettlementAuditEntity,
  TripEntity,
  TripRecurrenceRuleEntity,
  TripShareLinkEntity,
  UserDeviceEntity,
  UserEntity,
  VehicleEntity,
  WalletAccountEntity,
  WalletHoldEntity,
  WalletTransactionEntity,
} from './entities';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.POSTGRES_HOST || 'localhost',
  port: Number(process.env.POSTGRES_PORT || 5432),
  username: process.env.POSTGRES_USER || 'postgres',
  password: process.env.POSTGRES_PASSWORD || 'postgres',
  database: process.env.POSTGRES_DB || 'rideshare',
  ssl:
    process.env.POSTGRES_SSL === 'true' ? { rejectUnauthorized: false } : false,
  entities: [
    AccountFlagEntity,
    BookingEntity,
    BookingSeatEntity,
    CallSessionEntity,
    ChatRoomEntity,
    CommunicationFeeEntity,
    ComplaintEntity,
    DeviceTokenEntity,
    DriverLocationEntity,
    MessageEntity,
    NotificationEntity,
    OtpCodeEntity,
    PasswordResetSessionEntity,
    PaymentEntity,
    PayoutRequestEntity,
    PendingChargeEntity,
    PendingRegistrationEntity,
    RatingEntity,
    RefundRequestEntity,
    SecurityEventEntity,
    SettlementAuditEntity,
    TripEntity,
    TripRecurrenceRuleEntity,
    TripShareLinkEntity,
    UserDeviceEntity,
    UserEntity,
    VehicleEntity,
    WalletAccountEntity,
    WalletHoldEntity,
    WalletTransactionEntity,
  ],
  migrations: ['src/database/migrations/*.ts'],
  migrationsTransactionMode: 'each',
});
