import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  AccountFlagEntity,
  BookingEntity,
  BookingSeatEntity,
  CallSessionEntity,
  ChatRoomEntity,
  CommunicationFeeEntity,
  ComplaintEntity,
  DeviceTokenEntity,
  DriverLocationEntity,
  MessageEntity,
  NotificationEntity,
  OtpCodeEntity,
  PasswordResetSessionEntity,
  PaymentEntity,
  PayoutRequestEntity,
  PendingChargeEntity,
  PendingRegistrationEntity,
  RatingEntity,
  RefundRequestEntity,
  SecurityEventEntity,
  SettlementAuditEntity,
  TripEntity,
  TripRecurrenceRuleEntity,
  TripShareLinkEntity,
  UserDeviceEntity,
  UserEntity,
  VehicleEntity,
  WalletAccountEntity,
  WalletHoldEntity,
  WalletTransactionEntity,
} from './entities';

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        type: 'postgres',
        host: config.get<string>('POSTGRES_HOST', 'localhost'),
        port: Number(config.get<string>('POSTGRES_PORT', '5432')),
        username: config.get<string>('POSTGRES_USER', 'postgres'),
        password: config.get<string>('POSTGRES_PASSWORD', 'postgres'),
        database: config.get<string>('POSTGRES_DB', 'rideshare'),
        ssl:
          config.get<string>('POSTGRES_SSL', 'false') === 'true'
            ? { rejectUnauthorized: false }
            : false,
        entities: [
          AccountFlagEntity,
          BookingEntity,
          BookingSeatEntity,
          CallSessionEntity,
          ChatRoomEntity,
          CommunicationFeeEntity,
          ComplaintEntity,
          DeviceTokenEntity,
          DriverLocationEntity,
          MessageEntity,
          NotificationEntity,
          OtpCodeEntity,
          PasswordResetSessionEntity,
          PaymentEntity,
          PayoutRequestEntity,
          PendingChargeEntity,
          PendingRegistrationEntity,
          RatingEntity,
          RefundRequestEntity,
          SecurityEventEntity,
          SettlementAuditEntity,
          TripEntity,
          TripRecurrenceRuleEntity,
          TripShareLinkEntity,
          UserDeviceEntity,
          UserEntity,
          VehicleEntity,
          WalletAccountEntity,
          WalletHoldEntity,
          WalletTransactionEntity,
        ],
        synchronize: false,
        autoLoadEntities: true,
      }),
    }),
  ],
})
export class PostgresModule {}
