import 'vehicle_art.dart';

/// Seat rectangles measured against each vehicle asset, normalized to the
/// image so they hold at any render size.
///
/// Order matches the backend's `seatsPerRowList` flattening exactly - the nth
/// entry here is display seat n and backend seat id `row-col`.
///
/// The driver's seat is part of the artwork and is never overlaid: it is not
/// bookable, so it carries no state worth drawing.
///
/// GENERATED by scripts/calibrate_vehicle_art.py - do not hand-edit.
const Map<String, VehicleArt> kVehicleArtCatalog = {
  'standard_car': VehicleArt(
    asset: 'assets/vehicles/standard_car.png',
    aspectRatio: 0.6279, // 523x833
    seats: [
      SeatSlot(row: 0, col: 0, left: 0.5373, top: 0.2869, width: 0.2734, height: 0.1753),
      SeatSlot(row: 1, col: 0, left: 0.1931, top: 0.5102, width: 0.2045, height: 0.1861),
      SeatSlot(row: 1, col: 1, left: 0.3977, top: 0.5102, width: 0.2044, height: 0.1861),
      SeatSlot(row: 1, col: 2, left: 0.6023, top: 0.5102, width: 0.2065, height: 0.1861),
    ],
  ),
  'family_suv': VehicleArt(
    asset: 'assets/vehicles/family_suv.png',
    aspectRatio: 0.5947, // 534x898
    seats: [
      SeatSlot(row: 0, col: 0, left: 0.5449, top: 0.294, width: 0.2603, height: 0.1771),
      SeatSlot(row: 1, col: 0, left: 0.1742, top: 0.5022, width: 0.2171, height: 0.1604),
      SeatSlot(row: 1, col: 1, left: 0.3914, top: 0.5022, width: 0.2171, height: 0.1604),
      SeatSlot(row: 1, col: 2, left: 0.6086, top: 0.5022, width: 0.2191, height: 0.1604),
      SeatSlot(row: 2, col: 0, left: 0.2228, top: 0.6893, width: 0.2116, height: 0.1359),
      SeatSlot(row: 2, col: 1, left: 0.5655, top: 0.6893, width: 0.2097, height: 0.1359),
    ],
  ),
  'medium_bus': VehicleArt(
    asset: 'assets/vehicles/medium_bus.png',
    aspectRatio: 0.5499, // 281x511
    seats: [
      SeatSlot(row: 0, col: 0, left: 0.5658, top: 0.2524, width: 0.1886, height: 0.1233),
      SeatSlot(row: 1, col: 0, left: 0.2242, top: 0.3914, width: 0.1493, height: 0.1194),
      SeatSlot(row: 1, col: 1, left: 0.3737, top: 0.3914, width: 0.153, height: 0.1194),
      SeatSlot(row: 1, col: 2, left: 0.6014, top: 0.3914, width: 0.1673, height: 0.1194),
      SeatSlot(row: 2, col: 0, left: 0.2242, top: 0.5362, width: 0.1493, height: 0.1194),
      SeatSlot(row: 2, col: 1, left: 0.3737, top: 0.5362, width: 0.153, height: 0.1194),
      SeatSlot(row: 2, col: 2, left: 0.605, top: 0.5362, width: 0.1673, height: 0.1194),
      SeatSlot(row: 3, col: 0, left: 0.2384, top: 0.6869, width: 0.1744, height: 0.1233),
      SeatSlot(row: 3, col: 1, left: 0.4164, top: 0.6869, width: 0.1673, height: 0.1233),
      SeatSlot(row: 3, col: 2, left: 0.5872, top: 0.6869, width: 0.1744, height: 0.1233),
    ],
  ),
  'large_bus': VehicleArt(
    asset: 'assets/vehicles/large_bus.png',
    aspectRatio: 0.4858, // 375x772
    seats: [
      SeatSlot(row: 0, col: 0, left: 0.5973, top: 0.0997, width: 0.1627, height: 0.0622),
      SeatSlot(row: 1, col: 0, left: 0.192, top: 0.2073, width: 0.136, height: 0.0894),
      SeatSlot(row: 1, col: 1, left: 0.336, top: 0.2073, width: 0.1387, height: 0.0894),
      SeatSlot(row: 1, col: 2, left: 0.6133, top: 0.2176, width: 0.1387, height: 0.0907),
      SeatSlot(row: 2, col: 0, left: 0.1893, top: 0.3135, width: 0.1413, height: 0.0881),
      SeatSlot(row: 2, col: 1, left: 0.336, top: 0.3135, width: 0.1413, height: 0.0881),
      SeatSlot(row: 2, col: 2, left: 0.6267, top: 0.3497, width: 0.144, height: 0.0907),
      SeatSlot(row: 3, col: 0, left: 0.1893, top: 0.4236, width: 0.1413, height: 0.0881),
      SeatSlot(row: 3, col: 1, left: 0.336, top: 0.4236, width: 0.1413, height: 0.0881),
      SeatSlot(row: 3, col: 2, left: 0.6293, top: 0.4663, width: 0.1467, height: 0.0907),
      SeatSlot(row: 4, col: 0, left: 0.1867, top: 0.5259, width: 0.144, height: 0.0881),
      SeatSlot(row: 4, col: 1, left: 0.336, top: 0.5259, width: 0.1413, height: 0.0881),
      SeatSlot(row: 4, col: 2, left: 0.632, top: 0.5829, width: 0.1493, height: 0.092),
      SeatSlot(row: 5, col: 0, left: 0.1867, top: 0.6295, width: 0.1413, height: 0.0868),
      SeatSlot(row: 5, col: 1, left: 0.336, top: 0.6295, width: 0.1413, height: 0.0868),
      SeatSlot(row: 5, col: 2, left: 0.6347, top: 0.6969, width: 0.152, height: 0.0894),
      SeatSlot(row: 6, col: 0, left: 0.184, top: 0.7319, width: 0.144, height: 0.0842),
      SeatSlot(row: 6, col: 1, left: 0.3333, top: 0.7319, width: 0.144, height: 0.0842),
      SeatSlot(row: 7, col: 0, left: 0.1787, top: 0.8368, width: 0.1519, height: 0.1049),
      SeatSlot(row: 7, col: 1, left: 0.3307, top: 0.8368, width: 0.1519, height: 0.1049),
      SeatSlot(row: 7, col: 2, left: 0.4827, top: 0.8368, width: 0.1519, height: 0.1049),
      SeatSlot(row: 7, col: 3, left: 0.6347, top: 0.8368, width: 0.152, height: 0.1049),
    ],
  ),
};
