// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KS8J4CKop_tqTGdM-gk1e7GsxCS-sJ4',
    appId: '1:907014658060:web:1ffb633f83fa23e31f7629',
    messagingSenderId: '907014658060',
    projectId: 'rideshare-5f785',
    authDomain: 'rideshare-5f785.firebaseapp.com',
    storageBucket: 'rideshare-5f785.firebasestorage.app',
    measurementId: 'G-X2S9L8JKVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmifGoJxnbv8xX3ojbSGT35OwybN3T0w',
    appId: '1:907014658060:android:2376f0e8dc4dd5141f7629',
    messagingSenderId: '907014658060',
    projectId: 'rideshare-5f785',
    storageBucket: 'rideshare-5f785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDew_L5FY54usMO_ykeaahvla8yYlxkT-Q',
    appId: '1:907014658060:ios:f23dfaefdba34fb61f7629',
    messagingSenderId: '907014658060',
    projectId: 'rideshare-5f785',
    storageBucket: 'rideshare-5f785.firebasestorage.app',
    iosBundleId: 'com.abdelaziz.visionway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDew_L5FY54usMO_ykeaahvla8yYlxkT-Q',
    appId: '1:907014658060:ios:f23dfaefdba34fb61f7629',
    messagingSenderId: '907014658060',
    projectId: 'rideshare-5f785',
    storageBucket: 'rideshare-5f785.firebasestorage.app',
    iosBundleId: 'com.abdelaziz.visionway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KS8J4CKop_tqTGdM-gk1e7GsxCS-sJ4',
    appId: '1:907014658060:web:fa0332bbfa76a9a51f7629',
    messagingSenderId: '907014658060',
    projectId: 'rideshare-5f785',
    authDomain: 'rideshare-5f785.firebaseapp.com',
    storageBucket: 'rideshare-5f785.firebasestorage.app',
    measurementId: 'G-RLB7M04GVT',
  );
}
